sonar.projectKey=AndrejBokonjic_NALOGERIRS
sonar.organization=andrejbokonjic
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# Frontend coverage (Vitest)
sonar.javascript.lcov.reportPaths=gazeProReact/coverage/lcov.info

# Backend coverage (pytest)
sonar.python.coverage.reportPaths=backend/backend-coverage.xml
